M48
; DRILL file {KiCad 7.0.8-7.0.8~ubuntu22.04.1} date Sun 29 Oct 2023 15:12:25
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-10-29T15:12:25+11:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.8-7.0.8~ubuntu22.04.1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1181
%
G90
G05
T1
X3.9638Y-2.0472
X3.9638Y-2.4409
T0
M30
